compressionLevel: 0
enableGlobalCache: true
nodeLinker: pnp

# This is needed so that yarn downloads packages for all
# supported architectures into the cache which then allows
# the yarnpnp2nix plugin to get the hash of, say darwin
# package, when installing on Linux. An example is fsevents
# which is Darwin only, but it could also apply to esbuild
# which ships binaries for different platforms in separate
# sub-packages with os|cup conditions.
supportedArchitectures:
  os:
  - "current"
  - "darwin"
  - "linux"
  cpu:
  - "current"
  - "x64"
  - "arm64"
