# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "@types/node@npm:18.18.0" = {
      name = "@types/node";
      reference = "npm:18.18.0";
      linkType = "HARD";
      outputName = "types-node-18.18.0-6c59c15776";
      outputHash = "5bcd1bd9536394c2accba38892e3396892dc9926608bd81d98553b3e50a61edb8e1503bc42511dae1175aa770f7c0a9c0b1f92d064b59a77ff68d33e3122070a";
      flatName = "node";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:18.x";
      checksum = "10c0/5bcd1bd9536394c2accba38892e3396892dc9926608bd81d98553b3e50a61edb8e1503bc42511dae1175aa770f7c0a9c0b1f92d064b59a77ff68d33e3122070a";
    };
    "cross-spawn@npm:7.0.3" = {
      name = "cross-spawn";
      reference = "npm:7.0.3";
      linkType = "HARD";
      outputName = "cross-spawn-7.0.3-e4ff3e65b3";
      outputHash = "5738c312387081c98d69c98e105b6327b069197f864a60593245d64c8089c8a0a744e16349281210d56835bb9274130d825a78b2ad6853ca13cfbeffc0c31750";
      flatName = "cross-spawn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.0.3";
      checksum = "10c0/5738c312387081c98d69c98e105b6327b069197f864a60593245d64c8089c8a0a744e16349281210d56835bb9274130d825a78b2ad6853ca13cfbeffc0c31750";
      dependencies = {
        "path-key" = packages."path-key@npm:3.1.1";
        "shebang-command" = packages."shebang-command@npm:2.0.0";
        "which" = packages."which@npm:2.0.2";
      };
    };
    "data-uri-to-buffer@npm:4.0.1" = {
      name = "data-uri-to-buffer";
      reference = "npm:4.0.1";
      linkType = "HARD";
      outputName = "data-uri-to-buffer-4.0.1-5c66a78beb";
      outputHash = "20a6b93107597530d71d4cb285acee17f66bcdfc03fd81040921a81252f19db27588d87fc8fc69e1950c55cfb0bf8ae40d0e5e21d907230813eb5d5a7f9eb45b";
      flatName = "data-uri-to-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "10c0/20a6b93107597530d71d4cb285acee17f66bcdfc03fd81040921a81252f19db27588d87fc8fc69e1950c55cfb0bf8ae40d0e5e21d907230813eb5d5a7f9eb45b";
    };
    "dev-workshop-athens@workspace:." = {
      name = "dev-workshop-athens";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "dev-workshop-athens-0.0.1-aded28f622";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "dev-workshop-athens";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      dependencies = {
        "node-fetch" = packages."node-fetch@npm:3.3.2";
        "typescript" = packages."typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      };
      devDependencies = {
        "@types/node" = packages."@types/node@npm:18.18.0";
        "tsc-watch" = packages."tsc-watch@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4";
      };
    };
    "duplexer@npm:0.1.2" = {
      name = "duplexer";
      reference = "npm:0.1.2";
      linkType = "HARD";
      outputName = "duplexer-0.1.2-952c810235";
      outputHash = "c57bcd4bdf7e623abab2df43a7b5b23d18152154529d166c1e0da6bee341d84c432d157d7e97b32fecb1bf3a8b8857dd85ed81a915789f550637ed25b8e64fc2";
      flatName = "duplexer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.1.1";
      checksum = "10c0/c57bcd4bdf7e623abab2df43a7b5b23d18152154529d166c1e0da6bee341d84c432d157d7e97b32fecb1bf3a8b8857dd85ed81a915789f550637ed25b8e64fc2";
    };
    "event-stream@npm:3.3.4" = {
      name = "event-stream";
      reference = "npm:3.3.4";
      linkType = "HARD";
      outputName = "event-stream-3.3.4-5a4db234bf";
      outputHash = "c3ec4e1efc27ab3e73a98923f0a2fa9a19051b87068fea2f3d53d2e4e8c5cfdadf8c8a115b17f3d90b16a46432d396bad91b6e8d0cceb3e449be717a03b75209";
      flatName = "event-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:=3.3.4";
      checksum = "10c0/c3ec4e1efc27ab3e73a98923f0a2fa9a19051b87068fea2f3d53d2e4e8c5cfdadf8c8a115b17f3d90b16a46432d396bad91b6e8d0cceb3e449be717a03b75209";
      dependencies = {
        "duplexer" = packages."duplexer@npm:0.1.2";
        "from" = packages."from@npm:0.1.7";
        "map-stream" = packages."map-stream@npm:0.1.0";
        "pause-stream" = packages."pause-stream@npm:0.0.11";
        "split" = packages."split@npm:0.3.3";
        "stream-combiner" = packages."stream-combiner@npm:0.0.4";
        "through" = packages."through@npm:2.3.8";
      };
    };
    "fetch-blob@npm:3.2.0" = {
      name = "fetch-blob";
      reference = "npm:3.2.0";
      linkType = "HARD";
      outputName = "fetch-blob-3.2.0-28e01becfc";
      outputHash = "60054bf47bfa10fb0ba6cb7742acec2f37c1f56344f79a70bb8b1c48d77675927c720ff3191fa546410a0442c998d27ab05e9144c32d530d8a52fbe68f843b69";
      flatName = "fetch-blob";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.4";
      checksum = "10c0/60054bf47bfa10fb0ba6cb7742acec2f37c1f56344f79a70bb8b1c48d77675927c720ff3191fa546410a0442c998d27ab05e9144c32d530d8a52fbe68f843b69";
      dependencies = {
        "node-domexception" = packages."node-domexception@npm:1.0.0";
        "web-streams-polyfill" = packages."web-streams-polyfill@npm:3.2.1";
      };
    };
    "formdata-polyfill@npm:4.0.10" = {
      name = "formdata-polyfill";
      reference = "npm:4.0.10";
      linkType = "HARD";
      outputName = "formdata-polyfill-4.0.10-e03013c013";
      outputHash = "5392ec484f9ce0d5e0d52fb5a78e7486637d516179b0eb84d81389d7eccf9ca2f663079da56f761355c0a65792810e3b345dc24db9a8bbbcf24ef3c8c88570c6";
      flatName = "formdata-polyfill";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.10";
      checksum = "10c0/5392ec484f9ce0d5e0d52fb5a78e7486637d516179b0eb84d81389d7eccf9ca2f663079da56f761355c0a65792810e3b345dc24db9a8bbbcf24ef3c8c88570c6";
      dependencies = {
        "fetch-blob" = packages."fetch-blob@npm:3.2.0";
      };
    };
    "from@npm:0.1.7" = {
      name = "from";
      reference = "npm:0.1.7";
      linkType = "HARD";
      outputName = "from-0.1.7-6dcf14a57d";
      outputHash = "3aab5aea8fe8e1f12a5dee7f390d46a93431ce691b6222dcd5701c5d34378e51ca59b44967da1105a0f90fcdf5d7629d963d51e7ccd79827d19693bdcfb688d4";
      flatName = "from";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0";
      checksum = "10c0/3aab5aea8fe8e1f12a5dee7f390d46a93431ce691b6222dcd5701c5d34378e51ca59b44967da1105a0f90fcdf5d7629d963d51e7ccd79827d19693bdcfb688d4";
    };
    "isexe@npm:2.0.0" = {
      name = "isexe";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "isexe-2.0.0-b58870bd2e";
      outputHash = "228cfa503fadc2c31596ab06ed6aa82c9976eec2bfd83397e7eaf06d0ccf42cd1dfd6743bf9aeb01aebd4156d009994c5f76ea898d2832c1fe342da923ca457d";
      flatName = "isexe";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "10c0/228cfa503fadc2c31596ab06ed6aa82c9976eec2bfd83397e7eaf06d0ccf42cd1dfd6743bf9aeb01aebd4156d009994c5f76ea898d2832c1fe342da923ca457d";
    };
    "map-stream@npm:0.1.0" = {
      name = "map-stream";
      reference = "npm:0.1.0";
      linkType = "HARD";
      outputName = "map-stream-0.1.0-e44450fc62";
      outputHash = "7dd6debe511c1b55d9da75e1efa65a28b1252a2d8357938d2e49b412713c478efbaefb0cdf0ee0533540c3bf733e8f9f71e1a15aa0fe74bf71b64e75bf1576bd";
      flatName = "map-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.1.0";
      checksum = "10c0/7dd6debe511c1b55d9da75e1efa65a28b1252a2d8357938d2e49b412713c478efbaefb0cdf0ee0533540c3bf733e8f9f71e1a15aa0fe74bf71b64e75bf1576bd";
    };
    "node-cleanup@npm:2.1.2" = {
      name = "node-cleanup";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "node-cleanup-2.1.2-adfbc95778";
      outputHash = "c59077d7cac01f6315e4417e5d13523e43aa19965b14768581dbd06b37419323abe5f7171afe6aa52b7a483bdd0027e5a5f62a532a2ebec2a8c4cdf163736c92";
      flatName = "node-cleanup";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.1.2";
      checksum = "10c0/c59077d7cac01f6315e4417e5d13523e43aa19965b14768581dbd06b37419323abe5f7171afe6aa52b7a483bdd0027e5a5f62a532a2ebec2a8c4cdf163736c92";
    };
    "node-domexception@npm:1.0.0" = {
      name = "node-domexception";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "node-domexception-1.0.0-e1e813b76f";
      outputHash = "5e5d63cda29856402df9472335af4bb13875e1927ad3be861dc5ebde38917aecbf9ae337923777af52a48c426b70148815e890a5d72760f1b4d758cc671b1a2b";
      flatName = "node-domexception";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "10c0/5e5d63cda29856402df9472335af4bb13875e1927ad3be861dc5ebde38917aecbf9ae337923777af52a48c426b70148815e890a5d72760f1b4d758cc671b1a2b";
    };
    "node-fetch@npm:3.3.2" = {
      name = "node-fetch";
      reference = "npm:3.3.2";
      linkType = "HARD";
      outputName = "node-fetch-3.3.2-5267e015f2";
      outputHash = "f3d5e56190562221398c9f5750198b34cf6113aa304e34ee97c94fd300ec578b25b2c2906edba922050fce983338fde0d5d34fcb0fc3336ade5bd0e429ad7538";
      flatName = "node-fetch";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.3.2";
      checksum = "10c0/f3d5e56190562221398c9f5750198b34cf6113aa304e34ee97c94fd300ec578b25b2c2906edba922050fce983338fde0d5d34fcb0fc3336ade5bd0e429ad7538";
      dependencies = {
        "data-uri-to-buffer" = packages."data-uri-to-buffer@npm:4.0.1";
        "fetch-blob" = packages."fetch-blob@npm:3.2.0";
        "formdata-polyfill" = packages."formdata-polyfill@npm:4.0.10";
      };
    };
    "path-key@npm:3.1.1" = {
      name = "path-key";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "path-key-3.1.1-0e66ea8321";
      outputHash = "748c43efd5a569c039d7a00a03b58eecd1d75f3999f5a28303d75f521288df4823bc057d8784eb72358b2895a05f29a070bc9f1f17d28226cc4e62494cc58c4c";
      flatName = "path-key";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.0";
      checksum = "10c0/748c43efd5a569c039d7a00a03b58eecd1d75f3999f5a28303d75f521288df4823bc057d8784eb72358b2895a05f29a070bc9f1f17d28226cc4e62494cc58c4c";
    };
    "pause-stream@npm:0.0.11" = {
      name = "pause-stream";
      reference = "npm:0.0.11";
      linkType = "HARD";
      outputName = "pause-stream-0.0.11-d0e142313d";
      outputHash = "86f12c64cdaaa8e45ebaca4e39a478e1442db8b4beabc280b545bfaf79c0e2f33c51efb554aace5c069cc441c7b924ba484837b345eaa4ba6fc940d62f826802";
      flatName = "pause-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.0.11";
      checksum = "10c0/86f12c64cdaaa8e45ebaca4e39a478e1442db8b4beabc280b545bfaf79c0e2f33c51efb554aace5c069cc441c7b924ba484837b345eaa4ba6fc940d62f826802";
      dependencies = {
        "through" = packages."through@npm:2.3.8";
      };
    };
    "ps-tree@npm:1.2.0" = {
      name = "ps-tree";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "ps-tree-1.2.0-3975e95bd6";
      outputHash = "9d1c159e0890db5aa05f84d125193c2190a6c4ecd457596fd25e7611f8f747292a846459dcc0244e27d45529d4cea6d1010c3a2a087fad02624d12fdb7d97c22";
      flatName = "ps-tree";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.0";
      checksum = "10c0/9d1c159e0890db5aa05f84d125193c2190a6c4ecd457596fd25e7611f8f747292a846459dcc0244e27d45529d4cea6d1010c3a2a087fad02624d12fdb7d97c22";
      bin = {
        "ps-tree" = "./bin/ps-tree.js";
      };
      dependencies = {
        "event-stream" = packages."event-stream@npm:3.3.4";
      };
    };
    "shebang-command@npm:2.0.0" = {
      name = "shebang-command";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "shebang-command-2.0.0-eb2b01921d";
      outputHash = "a41692e7d89a553ef21d324a5cceb5f686d1f3c040759c50aab69688634688c5c327f26f3ecf7001ebfd78c01f3c7c0a11a7c8bfd0a8bc9f6240d4f40b224e4e";
      flatName = "shebang-command";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "10c0/a41692e7d89a553ef21d324a5cceb5f686d1f3c040759c50aab69688634688c5c327f26f3ecf7001ebfd78c01f3c7c0a11a7c8bfd0a8bc9f6240d4f40b224e4e";
      dependencies = {
        "shebang-regex" = packages."shebang-regex@npm:3.0.0";
      };
    };
    "shebang-regex@npm:3.0.0" = {
      name = "shebang-regex";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "shebang-regex-3.0.0-899a0cd65e";
      outputHash = "1dbed0726dd0e1152a92696c76c7f06084eb32a90f0528d11acd764043aacf76994b2fb30aa1291a21bd019d6699164d048286309a278855ee7bec06cf6fb690";
      flatName = "shebang-regex";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "10c0/1dbed0726dd0e1152a92696c76c7f06084eb32a90f0528d11acd764043aacf76994b2fb30aa1291a21bd019d6699164d048286309a278855ee7bec06cf6fb690";
    };
    "split@npm:0.3.3" = {
      name = "split";
      reference = "npm:0.3.3";
      linkType = "HARD";
      outputName = "split-0.3.3-847dc2ba97";
      outputHash = "88c09b1b4de84953bf5d6c153123a1fbb20addfea9381f70d27b4eb6b2bfbadf25d313f8f5d3fd727d5679b97bfe54da04766b91010f131635bf49e51d5db3fc";
      flatName = "split";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.3";
      checksum = "10c0/88c09b1b4de84953bf5d6c153123a1fbb20addfea9381f70d27b4eb6b2bfbadf25d313f8f5d3fd727d5679b97bfe54da04766b91010f131635bf49e51d5db3fc";
      dependencies = {
        "through" = packages."through@npm:2.3.8";
      };
    };
    "stream-combiner@npm:0.0.4" = {
      name = "stream-combiner";
      reference = "npm:0.0.4";
      linkType = "HARD";
      outputName = "stream-combiner-0.0.4-0176779791";
      outputHash = "8075a94c0eb0f20450a8236cb99d4ce3ea6e6a4b36d8baa7440b1a08cde6ffd227debadffaecd80993bd334282875d0e927ab5b88484625e01970dd251004ff5";
      flatName = "stream-combiner";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.0.4";
      checksum = "10c0/8075a94c0eb0f20450a8236cb99d4ce3ea6e6a4b36d8baa7440b1a08cde6ffd227debadffaecd80993bd334282875d0e927ab5b88484625e01970dd251004ff5";
      dependencies = {
        "duplexer" = packages."duplexer@npm:0.1.2";
      };
    };
    "string-argv@npm:0.3.2" = {
      name = "string-argv";
      reference = "npm:0.3.2";
      linkType = "HARD";
      outputName = "string-argv-0.3.2-6e057a88f1";
      outputHash = "75c02a83759ad1722e040b86823909d9a2fc75d15dd71ec4b537c3560746e33b5f5a07f7332d1e3f88319909f82190843aa2f0a0d8c8d591ec08e93d5b8dec82";
      flatName = "string-argv";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.3.1";
      checksum = "10c0/75c02a83759ad1722e040b86823909d9a2fc75d15dd71ec4b537c3560746e33b5f5a07f7332d1e3f88319909f82190843aa2f0a0d8c8d591ec08e93d5b8dec82";
    };
    "through@npm:2.3.8" = {
      name = "through";
      reference = "npm:2.3.8";
      linkType = "HARD";
      outputName = "through-2.3.8-df5f72a16e";
      outputHash = "4b09f3774099de0d4df26d95c5821a62faee32c7e96fb1f4ebd54a2d7c11c57fe88b0a0d49cf375de5fee5ae6bf4eb56dbbf29d07366864e2ee805349970d3cc";
      flatName = "through";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.3.1";
      checksum = "10c0/4b09f3774099de0d4df26d95c5821a62faee32c7e96fb1f4ebd54a2d7c11c57fe88b0a0d49cf375de5fee5ae6bf4eb56dbbf29d07366864e2ee805349970d3cc";
    };
    "tsc-watch@npm:6.0.4" = {
      name = "tsc-watch";
      reference = "npm:6.0.4";
      linkType = "HARD";
      outputName = "tsc-watch-6.0.4-ca8d5a229b";
      outputHash = "e6891283daa5f3f5b6bc26bd4de24d85664a24cb0b0b3f3c46ec7b3f1ad0f599da02f73023814b3285b8fb9810164b8a43ed693f2fc12bc85a72b15d020545cd";
      flatName = "tsc-watch";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.4";
      checksum = "10c0/e6891283daa5f3f5b6bc26bd4de24d85664a24cb0b0b3f3c46ec7b3f1ad0f599da02f73023814b3285b8fb9810164b8a43ed693f2fc12bc85a72b15d020545cd";
      bin = {
        "tsc-watch" = "dist/lib/tsc-watch.js";
      };
      dependencies = {
        "cross-spawn" = packages."cross-spawn@npm:7.0.3";
        "node-cleanup" = packages."node-cleanup@npm:2.1.2";
        "ps-tree" = packages."ps-tree@npm:1.2.0";
        "string-argv" = packages."string-argv@npm:0.3.2";
      };
      packagePeers = [
        "@types/typescript"
        "typescript"
      ];
    };
    "tsc-watch@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4" = {
      name = "tsc-watch";
      reference = "virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4";
      canonicalPackage = packages."tsc-watch@npm:6.0.4";
      dependencies = {
        "cross-spawn" = packages."cross-spawn@npm:7.0.3";
        "node-cleanup" = packages."node-cleanup@npm:2.1.2";
        "ps-tree" = packages."ps-tree@npm:1.2.0";
        "string-argv" = packages."string-argv@npm:0.3.2";
        "typescript" = packages."typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      };
    };
    "typescript@npm:5.1.6" = {
      name = "typescript";
      reference = "npm:5.1.6";
      linkType = "HARD";
      outputName = "typescript-5.1.6-b157762de3";
      outputHash = "45ac28e2df8365fd28dac42f5d62edfe69a7203d5ec646732cadc04065331f34f9078f81f150fde42ed9754eed6fa3b06a8f3523c40b821e557b727f1992e025";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:5.1.x";
      checksum = "10c0/45ac28e2df8365fd28dac42f5d62edfe69a7203d5ec646732cadc04065331f34f9078f81f150fde42ed9754eed6fa3b06a8f3523c40b821e557b727f1992e025";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071" = {
      name = "typescript";
      reference = "patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      linkType = "HARD";
      outputName = "typescript-5.1.6-97a611e52a";
      outputHash = "c2bded58ab897a8341fdbb0c1d92ea2362f498cfffebdc8a529d03e15ea2454142dfbf122dabbd9a5cb79b7123790d27def16e11844887d20636226773ed329a";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:typescript@npm%3A5.1.x#optional!builtin<compat/typescript>";
      checksum = "10c0/c2bded58ab897a8341fdbb0c1d92ea2362f498cfffebdc8a529d03e15ea2454142dfbf122dabbd9a5cb79b7123790d27def16e11844887d20636226773ed329a";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "web-streams-polyfill@npm:3.2.1" = {
      name = "web-streams-polyfill";
      reference = "npm:3.2.1";
      linkType = "HARD";
      outputName = "web-streams-polyfill-3.2.1-835bd3857e";
      outputHash = "70ed6b5708e14afa2ab699221ea197d7c68ec0c8274bbe0181aecc5ba636ca27cbd383d2049f0eb9d529e738f5c088825502b317f3df24d18a278e4cc9a10e8b";
      flatName = "web-streams-polyfill";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.3";
      checksum = "10c0/70ed6b5708e14afa2ab699221ea197d7c68ec0c8274bbe0181aecc5ba636ca27cbd383d2049f0eb9d529e738f5c088825502b317f3df24d18a278e4cc9a10e8b";
    };
    "which@npm:2.0.2" = {
      name = "which";
      reference = "npm:2.0.2";
      linkType = "HARD";
      outputName = "which-2.0.2-320ddf72f7";
      outputHash = "66522872a768b60c2a65a57e8ad184e5372f5b6a9ca6d5f033d4b0dc98aff63995655a7503b9c0a2598936f532120e81dd8cc155e2e92ed662a2b9377cc4374f";
      flatName = "which";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.1";
      checksum = "10c0/66522872a768b60c2a65a57e8ad184e5372f5b6a9ca6d5f033d4b0dc98aff63995655a7503b9c0a2598936f532120e81dd8cc155e2e92ed662a2b9377cc4374f";
      bin = {
        "node-which" = "./bin/node-which";
      };
      dependencies = {
        "isexe" = packages."isexe@npm:2.0.0";
      };
    };
  };
in
packages
