# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "@cspotcode/source-map-support@npm:0.8.1" = {
      name = "@cspotcode/source-map-support";
      reference = "npm:0.8.1";
      linkType = "HARD";
      outputName = "cspotcode-source-map-support-0.8.1-964f2de99d";
      outputHash = "05c5368c13b662ee4c122c7bfbe5dc0b613416672a829f3e78bc49a357a197e0218d6e74e7c66cfcd04e15a179acab080bd3c69658c9fbefd0e1ccd950a07fc6";
      flatName = "source-map-support";
      languageName = "node";
      scope = "cspotcode";
      descriptorRange = "npm:^0.8.0";
      checksum = "10c0/05c5368c13b662ee4c122c7bfbe5dc0b613416672a829f3e78bc49a357a197e0218d6e74e7c66cfcd04e15a179acab080bd3c69658c9fbefd0e1ccd950a07fc6";
      dependencies = {
        "@jridgewell/trace-mapping" = packages."@jridgewell/trace-mapping@npm:0.3.9";
      };
    };
    "@jridgewell/resolve-uri@npm:3.1.1" = {
      name = "@jridgewell/resolve-uri";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "jridgewell-resolve-uri-3.1.1-aa2de3f210";
      outputHash = "0dbc9e29bc640bbbdc5b9876d2859c69042bfcf1423c1e6421bcca53e826660bff4e41c7d4bcb8dbea696404231a6f902f76ba41835d049e20f2dd6cffb713bf";
      flatName = "resolve-uri";
      languageName = "node";
      scope = "jridgewell";
      descriptorRange = "npm:^3.0.3";
      checksum = "10c0/0dbc9e29bc640bbbdc5b9876d2859c69042bfcf1423c1e6421bcca53e826660bff4e41c7d4bcb8dbea696404231a6f902f76ba41835d049e20f2dd6cffb713bf";
    };
    "@jridgewell/sourcemap-codec@npm:1.4.15" = {
      name = "@jridgewell/sourcemap-codec";
      reference = "npm:1.4.15";
      linkType = "HARD";
      outputName = "jridgewell-sourcemap-codec-1.4.15-a055fb62cf";
      outputHash = "0c6b5ae663087558039052a626d2d7ed5208da36cfd707dcc5cea4a07cfc918248403dcb5989a8f7afaf245ce0573b7cc6fd94c4a30453bd10e44d9363940ba5";
      flatName = "sourcemap-codec";
      languageName = "node";
      scope = "jridgewell";
      descriptorRange = "npm:^1.4.10";
      checksum = "10c0/0c6b5ae663087558039052a626d2d7ed5208da36cfd707dcc5cea4a07cfc918248403dcb5989a8f7afaf245ce0573b7cc6fd94c4a30453bd10e44d9363940ba5";
    };
    "@jridgewell/trace-mapping@npm:0.3.9" = {
      name = "@jridgewell/trace-mapping";
      reference = "npm:0.3.9";
      linkType = "HARD";
      outputName = "jridgewell-trace-mapping-0.3.9-91625cd7fb";
      outputHash = "fa425b606d7c7ee5bfa6a31a7b050dd5814b4082f318e0e4190f991902181b4330f43f4805db1dd4f2433fd0ed9cc7a7b9c2683f1deeab1df1b0a98b1e24055b";
      flatName = "trace-mapping";
      languageName = "node";
      scope = "jridgewell";
      descriptorRange = "npm:0.3.9";
      checksum = "10c0/fa425b606d7c7ee5bfa6a31a7b050dd5814b4082f318e0e4190f991902181b4330f43f4805db1dd4f2433fd0ed9cc7a7b9c2683f1deeab1df1b0a98b1e24055b";
      dependencies = {
        "@jridgewell/resolve-uri" = packages."@jridgewell/resolve-uri@npm:3.1.1";
        "@jridgewell/sourcemap-codec" = packages."@jridgewell/sourcemap-codec@npm:1.4.15";
      };
    };
    "@tsconfig/node10@npm:1.0.9" = {
      name = "@tsconfig/node10";
      reference = "npm:1.0.9";
      linkType = "HARD";
      outputName = "tsconfig-node10-1.0.9-f2e2d20feb";
      outputHash = "c176a2c1e1b16be120c328300ea910df15fb9a5277010116d26818272341a11483c5a80059389d04edacf6fd2d03d4687ad3660870fdd1cc0b7109e160adb220";
      flatName = "node10";
      languageName = "node";
      scope = "tsconfig";
      descriptorRange = "npm:^1.0.7";
      checksum = "10c0/c176a2c1e1b16be120c328300ea910df15fb9a5277010116d26818272341a11483c5a80059389d04edacf6fd2d03d4687ad3660870fdd1cc0b7109e160adb220";
    };
    "@tsconfig/node12@npm:1.0.11" = {
      name = "@tsconfig/node12";
      reference = "npm:1.0.11";
      linkType = "HARD";
      outputName = "tsconfig-node12-1.0.11-9710d1c61b";
      outputHash = "dddca2b553e2bee1308a056705103fc8304e42bb2d2cbd797b84403a223b25c78f2c683ec3e24a095e82cd435387c877239bffcb15a590ba817cd3f6b9a99fd9";
      flatName = "node12";
      languageName = "node";
      scope = "tsconfig";
      descriptorRange = "npm:^1.0.7";
      checksum = "10c0/dddca2b553e2bee1308a056705103fc8304e42bb2d2cbd797b84403a223b25c78f2c683ec3e24a095e82cd435387c877239bffcb15a590ba817cd3f6b9a99fd9";
    };
    "@tsconfig/node14@npm:1.0.3" = {
      name = "@tsconfig/node14";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "tsconfig-node14-1.0.3-15321421d2";
      outputHash = "67c1316d065fdaa32525bc9449ff82c197c4c19092b9663b23213c8cbbf8d88b6ed6a17898e0cbc2711950fbfaf40388938c1c748a2ee89f7234fc9e7fe2bf44";
      flatName = "node14";
      languageName = "node";
      scope = "tsconfig";
      descriptorRange = "npm:^1.0.0";
      checksum = "10c0/67c1316d065fdaa32525bc9449ff82c197c4c19092b9663b23213c8cbbf8d88b6ed6a17898e0cbc2711950fbfaf40388938c1c748a2ee89f7234fc9e7fe2bf44";
    };
    "@tsconfig/node16@npm:1.0.4" = {
      name = "@tsconfig/node16";
      reference = "npm:1.0.4";
      linkType = "HARD";
      outputName = "tsconfig-node16-1.0.4-b7cb87d859";
      outputHash = "05f8f2734e266fb1839eb1d57290df1664fe2aa3b0fdd685a9035806daa635f7519bf6d5d9b33f6e69dd545b8c46bd6e2b5c79acb2b1f146e885f7f11a42a5bb";
      flatName = "node16";
      languageName = "node";
      scope = "tsconfig";
      descriptorRange = "npm:^1.0.2";
      checksum = "10c0/05f8f2734e266fb1839eb1d57290df1664fe2aa3b0fdd685a9035806daa635f7519bf6d5d9b33f6e69dd545b8c46bd6e2b5c79acb2b1f146e885f7f11a42a5bb";
    };
    "@types/node@npm:18.18.0" = {
      name = "@types/node";
      reference = "npm:18.18.0";
      linkType = "HARD";
      outputName = "types-node-18.18.0-6c59c15776";
      outputHash = "5bcd1bd9536394c2accba38892e3396892dc9926608bd81d98553b3e50a61edb8e1503bc42511dae1175aa770f7c0a9c0b1f92d064b59a77ff68d33e3122070a";
      flatName = "node";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:18.x";
      checksum = "10c0/5bcd1bd9536394c2accba38892e3396892dc9926608bd81d98553b3e50a61edb8e1503bc42511dae1175aa770f7c0a9c0b1f92d064b59a77ff68d33e3122070a";
    };
    "acorn-walk@npm:8.2.0" = {
      name = "acorn-walk";
      reference = "npm:8.2.0";
      linkType = "HARD";
      outputName = "acorn-walk-8.2.0-2f2cac3177";
      outputHash = "dbe92f5b2452c93e960c5594e666dd1fae141b965ff2cb4a1e1d0381e3e4db4274c5ce4ffa3d681a86ca2a8d4e29d5efc0670a08e23fd2800051ea387df56ca2";
      flatName = "acorn-walk";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^8.1.1";
      checksum = "10c0/dbe92f5b2452c93e960c5594e666dd1fae141b965ff2cb4a1e1d0381e3e4db4274c5ce4ffa3d681a86ca2a8d4e29d5efc0670a08e23fd2800051ea387df56ca2";
    };
    "acorn@npm:8.10.0" = {
      name = "acorn";
      reference = "npm:8.10.0";
      linkType = "HARD";
      outputName = "acorn-8.10.0-2230c9e83e";
      outputHash = "deaeebfbea6e40f6c0e1070e9b0e16e76ba484de54cbd735914d1d41d19169a450de8630b7a3a0c4e271a3b0c0b075a3427ad1a40d8a69f8747c0e8cb02ee3e2";
      flatName = "acorn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^8.4.1";
      checksum = "10c0/deaeebfbea6e40f6c0e1070e9b0e16e76ba484de54cbd735914d1d41d19169a450de8630b7a3a0c4e271a3b0c0b075a3427ad1a40d8a69f8747c0e8cb02ee3e2";
      bin = {
        "acorn" = "bin/acorn";
      };
    };
    "arg@npm:4.1.3" = {
      name = "arg";
      reference = "npm:4.1.3";
      linkType = "HARD";
      outputName = "arg-4.1.3-1748b966a8";
      outputHash = "070ff801a9d236a6caa647507bdcc7034530604844d64408149a26b9e87c2f97650055c0f049abd1efc024b334635c01f29e0b632b371ac3f26130f4cf65997a";
      flatName = "arg";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.1.0";
      checksum = "10c0/070ff801a9d236a6caa647507bdcc7034530604844d64408149a26b9e87c2f97650055c0f049abd1efc024b334635c01f29e0b632b371ac3f26130f4cf65997a";
    };
    "create-require@npm:1.1.1" = {
      name = "create-require";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "create-require-1.1.1-839884ca2e";
      outputHash = "157cbc59b2430ae9a90034a5f3a1b398b6738bf510f713edc4d4e45e169bc514d3d99dd34d8d01ca7ae7830b5b8b537e46ae8f3c8f932371b0875c0151d7ec91";
      flatName = "create-require";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.0";
      checksum = "10c0/157cbc59b2430ae9a90034a5f3a1b398b6738bf510f713edc4d4e45e169bc514d3d99dd34d8d01ca7ae7830b5b8b537e46ae8f3c8f932371b0875c0151d7ec91";
    };
    "cross-spawn@npm:7.0.3" = {
      name = "cross-spawn";
      reference = "npm:7.0.3";
      linkType = "HARD";
      outputName = "cross-spawn-7.0.3-e4ff3e65b3";
      outputHash = "5738c312387081c98d69c98e105b6327b069197f864a60593245d64c8089c8a0a744e16349281210d56835bb9274130d825a78b2ad6853ca13cfbeffc0c31750";
      flatName = "cross-spawn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^7.0.3";
      checksum = "10c0/5738c312387081c98d69c98e105b6327b069197f864a60593245d64c8089c8a0a744e16349281210d56835bb9274130d825a78b2ad6853ca13cfbeffc0c31750";
      dependencies = {
        "path-key" = packages."path-key@npm:3.1.1";
        "shebang-command" = packages."shebang-command@npm:2.0.0";
        "which" = packages."which@npm:2.0.2";
      };
    };
    "data-uri-to-buffer@npm:4.0.1" = {
      name = "data-uri-to-buffer";
      reference = "npm:4.0.1";
      linkType = "HARD";
      outputName = "data-uri-to-buffer-4.0.1-5c66a78beb";
      outputHash = "20a6b93107597530d71d4cb285acee17f66bcdfc03fd81040921a81252f19db27588d87fc8fc69e1950c55cfb0bf8ae40d0e5e21d907230813eb5d5a7f9eb45b";
      flatName = "data-uri-to-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "10c0/20a6b93107597530d71d4cb285acee17f66bcdfc03fd81040921a81252f19db27588d87fc8fc69e1950c55cfb0bf8ae40d0e5e21d907230813eb5d5a7f9eb45b";
    };
    "dev-workshop-athens@workspace:." = {
      name = "dev-workshop-athens";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "dev-workshop-athens-0.0.1-aded28f622";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "dev-workshop-athens";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      dependencies = {
        "node-fetch" = packages."node-fetch@npm:3.3.2";
        "typescript" = packages."typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      };
      devDependencies = {
        "@types/node" = packages."@types/node@npm:18.18.0";
        "ts-node" = packages."ts-node@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:10.9.1";
        "tsc-watch" = packages."tsc-watch@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4";
      };
    };
    "diff@npm:4.0.2" = {
      name = "diff";
      reference = "npm:4.0.2";
      linkType = "HARD";
      outputName = "diff-4.0.2-73133c7102";
      outputHash = "81b91f9d39c4eaca068eb0c1eb0e4afbdc5bb2941d197f513dd596b820b956fef43485876226d65d497bebc15666aa2aa82c679e84f65d5f2bfbf14ee46e32c1";
      flatName = "diff";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.1";
      checksum = "10c0/81b91f9d39c4eaca068eb0c1eb0e4afbdc5bb2941d197f513dd596b820b956fef43485876226d65d497bebc15666aa2aa82c679e84f65d5f2bfbf14ee46e32c1";
    };
    "duplexer@npm:0.1.2" = {
      name = "duplexer";
      reference = "npm:0.1.2";
      linkType = "HARD";
      outputName = "duplexer-0.1.2-952c810235";
      outputHash = "c57bcd4bdf7e623abab2df43a7b5b23d18152154529d166c1e0da6bee341d84c432d157d7e97b32fecb1bf3a8b8857dd85ed81a915789f550637ed25b8e64fc2";
      flatName = "duplexer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.1.1";
      checksum = "10c0/c57bcd4bdf7e623abab2df43a7b5b23d18152154529d166c1e0da6bee341d84c432d157d7e97b32fecb1bf3a8b8857dd85ed81a915789f550637ed25b8e64fc2";
    };
    "event-stream@npm:3.3.4" = {
      name = "event-stream";
      reference = "npm:3.3.4";
      linkType = "HARD";
      outputName = "event-stream-3.3.4-5a4db234bf";
      outputHash = "c3ec4e1efc27ab3e73a98923f0a2fa9a19051b87068fea2f3d53d2e4e8c5cfdadf8c8a115b17f3d90b16a46432d396bad91b6e8d0cceb3e449be717a03b75209";
      flatName = "event-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:=3.3.4";
      checksum = "10c0/c3ec4e1efc27ab3e73a98923f0a2fa9a19051b87068fea2f3d53d2e4e8c5cfdadf8c8a115b17f3d90b16a46432d396bad91b6e8d0cceb3e449be717a03b75209";
      dependencies = {
        "duplexer" = packages."duplexer@npm:0.1.2";
        "from" = packages."from@npm:0.1.7";
        "map-stream" = packages."map-stream@npm:0.1.0";
        "pause-stream" = packages."pause-stream@npm:0.0.11";
        "split" = packages."split@npm:0.3.3";
        "stream-combiner" = packages."stream-combiner@npm:0.0.4";
        "through" = packages."through@npm:2.3.8";
      };
    };
    "fetch-blob@npm:3.2.0" = {
      name = "fetch-blob";
      reference = "npm:3.2.0";
      linkType = "HARD";
      outputName = "fetch-blob-3.2.0-28e01becfc";
      outputHash = "60054bf47bfa10fb0ba6cb7742acec2f37c1f56344f79a70bb8b1c48d77675927c720ff3191fa546410a0442c998d27ab05e9144c32d530d8a52fbe68f843b69";
      flatName = "fetch-blob";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.4";
      checksum = "10c0/60054bf47bfa10fb0ba6cb7742acec2f37c1f56344f79a70bb8b1c48d77675927c720ff3191fa546410a0442c998d27ab05e9144c32d530d8a52fbe68f843b69";
      dependencies = {
        "node-domexception" = packages."node-domexception@npm:1.0.0";
        "web-streams-polyfill" = packages."web-streams-polyfill@npm:3.2.1";
      };
    };
    "formdata-polyfill@npm:4.0.10" = {
      name = "formdata-polyfill";
      reference = "npm:4.0.10";
      linkType = "HARD";
      outputName = "formdata-polyfill-4.0.10-e03013c013";
      outputHash = "5392ec484f9ce0d5e0d52fb5a78e7486637d516179b0eb84d81389d7eccf9ca2f663079da56f761355c0a65792810e3b345dc24db9a8bbbcf24ef3c8c88570c6";
      flatName = "formdata-polyfill";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.10";
      checksum = "10c0/5392ec484f9ce0d5e0d52fb5a78e7486637d516179b0eb84d81389d7eccf9ca2f663079da56f761355c0a65792810e3b345dc24db9a8bbbcf24ef3c8c88570c6";
      dependencies = {
        "fetch-blob" = packages."fetch-blob@npm:3.2.0";
      };
    };
    "from@npm:0.1.7" = {
      name = "from";
      reference = "npm:0.1.7";
      linkType = "HARD";
      outputName = "from-0.1.7-6dcf14a57d";
      outputHash = "3aab5aea8fe8e1f12a5dee7f390d46a93431ce691b6222dcd5701c5d34378e51ca59b44967da1105a0f90fcdf5d7629d963d51e7ccd79827d19693bdcfb688d4";
      flatName = "from";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0";
      checksum = "10c0/3aab5aea8fe8e1f12a5dee7f390d46a93431ce691b6222dcd5701c5d34378e51ca59b44967da1105a0f90fcdf5d7629d963d51e7ccd79827d19693bdcfb688d4";
    };
    "isexe@npm:2.0.0" = {
      name = "isexe";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "isexe-2.0.0-b58870bd2e";
      outputHash = "228cfa503fadc2c31596ab06ed6aa82c9976eec2bfd83397e7eaf06d0ccf42cd1dfd6743bf9aeb01aebd4156d009994c5f76ea898d2832c1fe342da923ca457d";
      flatName = "isexe";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "10c0/228cfa503fadc2c31596ab06ed6aa82c9976eec2bfd83397e7eaf06d0ccf42cd1dfd6743bf9aeb01aebd4156d009994c5f76ea898d2832c1fe342da923ca457d";
    };
    "make-error@npm:1.3.6" = {
      name = "make-error";
      reference = "npm:1.3.6";
      linkType = "HARD";
      outputName = "make-error-1.3.6-ccb85d9458";
      outputHash = "171e458d86854c6b3fc46610cfacf0b45149ba043782558c6875d9f42f222124384ad0b468c92e996d815a8a2003817a710c0a160e49c1c394626f76fa45396f";
      flatName = "make-error";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.1";
      checksum = "10c0/171e458d86854c6b3fc46610cfacf0b45149ba043782558c6875d9f42f222124384ad0b468c92e996d815a8a2003817a710c0a160e49c1c394626f76fa45396f";
    };
    "map-stream@npm:0.1.0" = {
      name = "map-stream";
      reference = "npm:0.1.0";
      linkType = "HARD";
      outputName = "map-stream-0.1.0-e44450fc62";
      outputHash = "7dd6debe511c1b55d9da75e1efa65a28b1252a2d8357938d2e49b412713c478efbaefb0cdf0ee0533540c3bf733e8f9f71e1a15aa0fe74bf71b64e75bf1576bd";
      flatName = "map-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.1.0";
      checksum = "10c0/7dd6debe511c1b55d9da75e1efa65a28b1252a2d8357938d2e49b412713c478efbaefb0cdf0ee0533540c3bf733e8f9f71e1a15aa0fe74bf71b64e75bf1576bd";
    };
    "node-cleanup@npm:2.1.2" = {
      name = "node-cleanup";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "node-cleanup-2.1.2-adfbc95778";
      outputHash = "c59077d7cac01f6315e4417e5d13523e43aa19965b14768581dbd06b37419323abe5f7171afe6aa52b7a483bdd0027e5a5f62a532a2ebec2a8c4cdf163736c92";
      flatName = "node-cleanup";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.1.2";
      checksum = "10c0/c59077d7cac01f6315e4417e5d13523e43aa19965b14768581dbd06b37419323abe5f7171afe6aa52b7a483bdd0027e5a5f62a532a2ebec2a8c4cdf163736c92";
    };
    "node-domexception@npm:1.0.0" = {
      name = "node-domexception";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "node-domexception-1.0.0-e1e813b76f";
      outputHash = "5e5d63cda29856402df9472335af4bb13875e1927ad3be861dc5ebde38917aecbf9ae337923777af52a48c426b70148815e890a5d72760f1b4d758cc671b1a2b";
      flatName = "node-domexception";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "10c0/5e5d63cda29856402df9472335af4bb13875e1927ad3be861dc5ebde38917aecbf9ae337923777af52a48c426b70148815e890a5d72760f1b4d758cc671b1a2b";
    };
    "node-fetch@npm:3.3.2" = {
      name = "node-fetch";
      reference = "npm:3.3.2";
      linkType = "HARD";
      outputName = "node-fetch-3.3.2-5267e015f2";
      outputHash = "f3d5e56190562221398c9f5750198b34cf6113aa304e34ee97c94fd300ec578b25b2c2906edba922050fce983338fde0d5d34fcb0fc3336ade5bd0e429ad7538";
      flatName = "node-fetch";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.3.2";
      checksum = "10c0/f3d5e56190562221398c9f5750198b34cf6113aa304e34ee97c94fd300ec578b25b2c2906edba922050fce983338fde0d5d34fcb0fc3336ade5bd0e429ad7538";
      dependencies = {
        "data-uri-to-buffer" = packages."data-uri-to-buffer@npm:4.0.1";
        "fetch-blob" = packages."fetch-blob@npm:3.2.0";
        "formdata-polyfill" = packages."formdata-polyfill@npm:4.0.10";
      };
    };
    "path-key@npm:3.1.1" = {
      name = "path-key";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "path-key-3.1.1-0e66ea8321";
      outputHash = "748c43efd5a569c039d7a00a03b58eecd1d75f3999f5a28303d75f521288df4823bc057d8784eb72358b2895a05f29a070bc9f1f17d28226cc4e62494cc58c4c";
      flatName = "path-key";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.0";
      checksum = "10c0/748c43efd5a569c039d7a00a03b58eecd1d75f3999f5a28303d75f521288df4823bc057d8784eb72358b2895a05f29a070bc9f1f17d28226cc4e62494cc58c4c";
    };
    "pause-stream@npm:0.0.11" = {
      name = "pause-stream";
      reference = "npm:0.0.11";
      linkType = "HARD";
      outputName = "pause-stream-0.0.11-d0e142313d";
      outputHash = "86f12c64cdaaa8e45ebaca4e39a478e1442db8b4beabc280b545bfaf79c0e2f33c51efb554aace5c069cc441c7b924ba484837b345eaa4ba6fc940d62f826802";
      flatName = "pause-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.0.11";
      checksum = "10c0/86f12c64cdaaa8e45ebaca4e39a478e1442db8b4beabc280b545bfaf79c0e2f33c51efb554aace5c069cc441c7b924ba484837b345eaa4ba6fc940d62f826802";
      dependencies = {
        "through" = packages."through@npm:2.3.8";
      };
    };
    "ps-tree@npm:1.2.0" = {
      name = "ps-tree";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "ps-tree-1.2.0-3975e95bd6";
      outputHash = "9d1c159e0890db5aa05f84d125193c2190a6c4ecd457596fd25e7611f8f747292a846459dcc0244e27d45529d4cea6d1010c3a2a087fad02624d12fdb7d97c22";
      flatName = "ps-tree";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.0";
      checksum = "10c0/9d1c159e0890db5aa05f84d125193c2190a6c4ecd457596fd25e7611f8f747292a846459dcc0244e27d45529d4cea6d1010c3a2a087fad02624d12fdb7d97c22";
      bin = {
        "ps-tree" = "./bin/ps-tree.js";
      };
      dependencies = {
        "event-stream" = packages."event-stream@npm:3.3.4";
      };
    };
    "shebang-command@npm:2.0.0" = {
      name = "shebang-command";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "shebang-command-2.0.0-eb2b01921d";
      outputHash = "a41692e7d89a553ef21d324a5cceb5f686d1f3c040759c50aab69688634688c5c327f26f3ecf7001ebfd78c01f3c7c0a11a7c8bfd0a8bc9f6240d4f40b224e4e";
      flatName = "shebang-command";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.0";
      checksum = "10c0/a41692e7d89a553ef21d324a5cceb5f686d1f3c040759c50aab69688634688c5c327f26f3ecf7001ebfd78c01f3c7c0a11a7c8bfd0a8bc9f6240d4f40b224e4e";
      dependencies = {
        "shebang-regex" = packages."shebang-regex@npm:3.0.0";
      };
    };
    "shebang-regex@npm:3.0.0" = {
      name = "shebang-regex";
      reference = "npm:3.0.0";
      linkType = "HARD";
      outputName = "shebang-regex-3.0.0-899a0cd65e";
      outputHash = "1dbed0726dd0e1152a92696c76c7f06084eb32a90f0528d11acd764043aacf76994b2fb30aa1291a21bd019d6699164d048286309a278855ee7bec06cf6fb690";
      flatName = "shebang-regex";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.0";
      checksum = "10c0/1dbed0726dd0e1152a92696c76c7f06084eb32a90f0528d11acd764043aacf76994b2fb30aa1291a21bd019d6699164d048286309a278855ee7bec06cf6fb690";
    };
    "split@npm:0.3.3" = {
      name = "split";
      reference = "npm:0.3.3";
      linkType = "HARD";
      outputName = "split-0.3.3-847dc2ba97";
      outputHash = "88c09b1b4de84953bf5d6c153123a1fbb20addfea9381f70d27b4eb6b2bfbadf25d313f8f5d3fd727d5679b97bfe54da04766b91010f131635bf49e51d5db3fc";
      flatName = "split";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.3";
      checksum = "10c0/88c09b1b4de84953bf5d6c153123a1fbb20addfea9381f70d27b4eb6b2bfbadf25d313f8f5d3fd727d5679b97bfe54da04766b91010f131635bf49e51d5db3fc";
      dependencies = {
        "through" = packages."through@npm:2.3.8";
      };
    };
    "stream-combiner@npm:0.0.4" = {
      name = "stream-combiner";
      reference = "npm:0.0.4";
      linkType = "HARD";
      outputName = "stream-combiner-0.0.4-0176779791";
      outputHash = "8075a94c0eb0f20450a8236cb99d4ce3ea6e6a4b36d8baa7440b1a08cde6ffd227debadffaecd80993bd334282875d0e927ab5b88484625e01970dd251004ff5";
      flatName = "stream-combiner";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~0.0.4";
      checksum = "10c0/8075a94c0eb0f20450a8236cb99d4ce3ea6e6a4b36d8baa7440b1a08cde6ffd227debadffaecd80993bd334282875d0e927ab5b88484625e01970dd251004ff5";
      dependencies = {
        "duplexer" = packages."duplexer@npm:0.1.2";
      };
    };
    "string-argv@npm:0.3.2" = {
      name = "string-argv";
      reference = "npm:0.3.2";
      linkType = "HARD";
      outputName = "string-argv-0.3.2-6e057a88f1";
      outputHash = "75c02a83759ad1722e040b86823909d9a2fc75d15dd71ec4b537c3560746e33b5f5a07f7332d1e3f88319909f82190843aa2f0a0d8c8d591ec08e93d5b8dec82";
      flatName = "string-argv";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.3.1";
      checksum = "10c0/75c02a83759ad1722e040b86823909d9a2fc75d15dd71ec4b537c3560746e33b5f5a07f7332d1e3f88319909f82190843aa2f0a0d8c8d591ec08e93d5b8dec82";
    };
    "through@npm:2.3.8" = {
      name = "through";
      reference = "npm:2.3.8";
      linkType = "HARD";
      outputName = "through-2.3.8-df5f72a16e";
      outputHash = "4b09f3774099de0d4df26d95c5821a62faee32c7e96fb1f4ebd54a2d7c11c57fe88b0a0d49cf375de5fee5ae6bf4eb56dbbf29d07366864e2ee805349970d3cc";
      flatName = "through";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.3.1";
      checksum = "10c0/4b09f3774099de0d4df26d95c5821a62faee32c7e96fb1f4ebd54a2d7c11c57fe88b0a0d49cf375de5fee5ae6bf4eb56dbbf29d07366864e2ee805349970d3cc";
    };
    "ts-node@npm:10.9.1" = {
      name = "ts-node";
      reference = "npm:10.9.1";
      linkType = "HARD";
      outputName = "ts-node-10.9.1-6c268be7f4";
      outputHash = "95187932fb83f3901e22546bd2feeac7d2feb4f412f42ac3a595f049a23e8dcf70516dffb51866391228ea2dbcfaea039e250fb2bb334d48a86ab2b6aea0ae2d";
      flatName = "ts-node";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^10.9.1";
      checksum = "10c0/95187932fb83f3901e22546bd2feeac7d2feb4f412f42ac3a595f049a23e8dcf70516dffb51866391228ea2dbcfaea039e250fb2bb334d48a86ab2b6aea0ae2d";
      bin = {
        "ts-node" = "dist/bin.js";
        "ts-node-cwd" = "dist/bin-cwd.js";
        "ts-node-esm" = "dist/bin-esm.js";
        "ts-node-script" = "dist/bin-script.js";
        "ts-node-transpile-only" = "dist/bin-transpile.js";
        "ts-script" = "dist/bin-script-deprecated.js";
      };
      dependencies = {
        "@cspotcode/source-map-support" = packages."@cspotcode/source-map-support@npm:0.8.1";
        "@tsconfig/node10" = packages."@tsconfig/node10@npm:1.0.9";
        "@tsconfig/node12" = packages."@tsconfig/node12@npm:1.0.11";
        "@tsconfig/node14" = packages."@tsconfig/node14@npm:1.0.3";
        "@tsconfig/node16" = packages."@tsconfig/node16@npm:1.0.4";
        "acorn-walk" = packages."acorn-walk@npm:8.2.0";
        "acorn" = packages."acorn@npm:8.10.0";
        "arg" = packages."arg@npm:4.1.3";
        "create-require" = packages."create-require@npm:1.1.1";
        "diff" = packages."diff@npm:4.0.2";
        "make-error" = packages."make-error@npm:1.3.6";
        "v8-compile-cache-lib" = packages."v8-compile-cache-lib@npm:3.0.1";
        "yn" = packages."yn@npm:3.1.1";
      };
      packagePeers = [
        "@swc/core"
        "@swc/wasm"
        "@types/node"
        "@types/swc__core"
        "@types/swc__wasm"
        "@types/typescript"
        "typescript"
      ];
    };
    "ts-node@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:10.9.1" = {
      name = "ts-node";
      reference = "virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:10.9.1";
      canonicalPackage = packages."ts-node@npm:10.9.1";
      dependencies = {
        "@cspotcode/source-map-support" = packages."@cspotcode/source-map-support@npm:0.8.1";
        "@tsconfig/node10" = packages."@tsconfig/node10@npm:1.0.9";
        "@tsconfig/node12" = packages."@tsconfig/node12@npm:1.0.11";
        "@tsconfig/node14" = packages."@tsconfig/node14@npm:1.0.3";
        "@tsconfig/node16" = packages."@tsconfig/node16@npm:1.0.4";
        "@types/node" = packages."@types/node@npm:18.18.0";
        "acorn" = packages."acorn@npm:8.10.0";
        "acorn-walk" = packages."acorn-walk@npm:8.2.0";
        "arg" = packages."arg@npm:4.1.3";
        "create-require" = packages."create-require@npm:1.1.1";
        "diff" = packages."diff@npm:4.0.2";
        "make-error" = packages."make-error@npm:1.3.6";
        "typescript" = packages."typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
        "v8-compile-cache-lib" = packages."v8-compile-cache-lib@npm:3.0.1";
        "yn" = packages."yn@npm:3.1.1";
      };
    };
    "tsc-watch@npm:6.0.4" = {
      name = "tsc-watch";
      reference = "npm:6.0.4";
      linkType = "HARD";
      outputName = "tsc-watch-6.0.4-ca8d5a229b";
      outputHash = "e6891283daa5f3f5b6bc26bd4de24d85664a24cb0b0b3f3c46ec7b3f1ad0f599da02f73023814b3285b8fb9810164b8a43ed693f2fc12bc85a72b15d020545cd";
      flatName = "tsc-watch";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^6.0.4";
      checksum = "10c0/e6891283daa5f3f5b6bc26bd4de24d85664a24cb0b0b3f3c46ec7b3f1ad0f599da02f73023814b3285b8fb9810164b8a43ed693f2fc12bc85a72b15d020545cd";
      bin = {
        "tsc-watch" = "dist/lib/tsc-watch.js";
      };
      dependencies = {
        "cross-spawn" = packages."cross-spawn@npm:7.0.3";
        "node-cleanup" = packages."node-cleanup@npm:2.1.2";
        "ps-tree" = packages."ps-tree@npm:1.2.0";
        "string-argv" = packages."string-argv@npm:0.3.2";
      };
      packagePeers = [
        "@types/typescript"
        "typescript"
      ];
    };
    "tsc-watch@virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4" = {
      name = "tsc-watch";
      reference = "virtual:aded28f622b96723fd7cc382ec602cf00842bdf9bd8ebc7a63761e0335044d9342f70cdd6260abd1ba314a29ad55ae6b08bcf07cd7c3c55e1a9d59600eaed39f#npm:6.0.4";
      canonicalPackage = packages."tsc-watch@npm:6.0.4";
      dependencies = {
        "cross-spawn" = packages."cross-spawn@npm:7.0.3";
        "node-cleanup" = packages."node-cleanup@npm:2.1.2";
        "ps-tree" = packages."ps-tree@npm:1.2.0";
        "string-argv" = packages."string-argv@npm:0.3.2";
        "typescript" = packages."typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      };
    };
    "typescript@npm:5.1.6" = {
      name = "typescript";
      reference = "npm:5.1.6";
      linkType = "HARD";
      outputName = "typescript-5.1.6-b157762de3";
      outputHash = "45ac28e2df8365fd28dac42f5d62edfe69a7203d5ec646732cadc04065331f34f9078f81f150fde42ed9754eed6fa3b06a8f3523c40b821e557b727f1992e025";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:5.1.x";
      checksum = "10c0/45ac28e2df8365fd28dac42f5d62edfe69a7203d5ec646732cadc04065331f34f9078f81f150fde42ed9754eed6fa3b06a8f3523c40b821e557b727f1992e025";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "typescript@patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071" = {
      name = "typescript";
      reference = "patch:typescript@npm%3A5.1.6#optional!builtin<compat/typescript>::version=5.1.6&hash=5da071";
      linkType = "HARD";
      outputName = "typescript-5.1.6-97a611e52a";
      outputHash = "c2bded58ab897a8341fdbb0c1d92ea2362f498cfffebdc8a529d03e15ea2454142dfbf122dabbd9a5cb79b7123790d27def16e11844887d20636226773ed329a";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:typescript@npm%3A5.1.x#optional!builtin<compat/typescript>";
      checksum = "10c0/c2bded58ab897a8341fdbb0c1d92ea2362f498cfffebdc8a529d03e15ea2454142dfbf122dabbd9a5cb79b7123790d27def16e11844887d20636226773ed329a";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "v8-compile-cache-lib@npm:3.0.1" = {
      name = "v8-compile-cache-lib";
      reference = "npm:3.0.1";
      linkType = "HARD";
      outputName = "v8-compile-cache-lib-3.0.1-4886071ece";
      outputHash = "bdc36fb8095d3b41df197f5fb6f11e3a26adf4059df3213e3baa93810d8f0cc76f9a74aaefc18b73e91fe7e19154ed6f134eda6fded2e0f1c8d2272ed2d2d391";
      flatName = "v8-compile-cache-lib";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.1";
      checksum = "10c0/bdc36fb8095d3b41df197f5fb6f11e3a26adf4059df3213e3baa93810d8f0cc76f9a74aaefc18b73e91fe7e19154ed6f134eda6fded2e0f1c8d2272ed2d2d391";
    };
    "web-streams-polyfill@npm:3.2.1" = {
      name = "web-streams-polyfill";
      reference = "npm:3.2.1";
      linkType = "HARD";
      outputName = "web-streams-polyfill-3.2.1-835bd3857e";
      outputHash = "70ed6b5708e14afa2ab699221ea197d7c68ec0c8274bbe0181aecc5ba636ca27cbd383d2049f0eb9d529e738f5c088825502b317f3df24d18a278e4cc9a10e8b";
      flatName = "web-streams-polyfill";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.0.3";
      checksum = "10c0/70ed6b5708e14afa2ab699221ea197d7c68ec0c8274bbe0181aecc5ba636ca27cbd383d2049f0eb9d529e738f5c088825502b317f3df24d18a278e4cc9a10e8b";
    };
    "which@npm:2.0.2" = {
      name = "which";
      reference = "npm:2.0.2";
      linkType = "HARD";
      outputName = "which-2.0.2-320ddf72f7";
      outputHash = "66522872a768b60c2a65a57e8ad184e5372f5b6a9ca6d5f033d4b0dc98aff63995655a7503b9c0a2598936f532120e81dd8cc155e2e92ed662a2b9377cc4374f";
      flatName = "which";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.0.1";
      checksum = "10c0/66522872a768b60c2a65a57e8ad184e5372f5b6a9ca6d5f033d4b0dc98aff63995655a7503b9c0a2598936f532120e81dd8cc155e2e92ed662a2b9377cc4374f";
      bin = {
        "node-which" = "./bin/node-which";
      };
      dependencies = {
        "isexe" = packages."isexe@npm:2.0.0";
      };
    };
    "yn@npm:3.1.1" = {
      name = "yn";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "yn-3.1.1-8ad4259784";
      outputHash = "0732468dd7622ed8a274f640f191f3eaf1f39d5349a1b72836df484998d7d9807fbea094e2f5486d6b0cd2414aad5775972df0e68f8604db89a239f0f4bf7443";
      flatName = "yn";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:3.1.1";
      checksum = "10c0/0732468dd7622ed8a274f640f191f3eaf1f39d5349a1b72836df484998d7d9807fbea094e2f5486d6b0cd2414aad5775972df0e68f8604db89a239f0f4bf7443";
    };
  };
in
packages
